
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: upgrade-group
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create



  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jackson:
    time-zone: UTC

island:
  kafka:
    reserve-topic: reserveTopic


